import { Inter } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import Layout from "@/components/Layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Todo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Layout>
        <body className={inter.className}>{children}</body>
      </Layout>
    </html>
  );
}
